# Generated by Django 3.0.2 on 2020-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200404_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='defaultUser.jpeg', upload_to='images/'),
        ),
    ]
