# Generated by Django 3.0.2 on 2020-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200404_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/images/defaultUser.jpeg', upload_to='images/'),
        ),
    ]
