# Generated by Django 3.0.2 on 2020-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200405_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
