# Generated by Django 3.0.2 on 2020-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200405_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, help_text='Enter field documentation', max_length=20),
        ),
    ]
